### ISSUE TITLE
Environment variables from .travis.yml are not set in PR from a fork

### ISSUE THREAD

**Issue by jpopelka** [user-cont/release-bot#104]
Compare [this](https://travis-ci.org/user-cont/release-bot/builds/443115552) and [this](https://travis-ci.org/user-cont/release-bot/builds/443095739).

In the second you can see
```
Setting environment variables from .travis.yml
$ export GITHUB_USER=[secure]
$ export GITHUB_TOKEN=[secure]
```

while in the first case the variables are not set and some important tests are skipped.

The first case is #103 (PR from my fork), while the second is #102 (PR from upstream branch).

**Comment by jpopelka** [comment]
From [Encryption keys](https://docs.travis-ci.com/user/encryption-keys/):
"Please note that encrypted environment variables are not available for [pull requests from forks](https://docs.travis-ci.com/user/pull-requests#Pull-Requests-and-Security-Restrictions)."

**Comment by TomasTomecek** [comment]
time to use centos ci?

**Comment by jpopelka** [comment]
Closing, since there's no way to fix this.

Yeah, cico time.
