### ISSUE TITLE
Bodhi updates submission

### ISSUE THREAD

**Issue by kosciCZ** [user-cont/release-bot#11]
Add this feature

**Comment by kosciCZ** [comment]
Postponed due to waiting for fedora keytab ([ticket](https://pagure.io/fedora-infrastructure/issue/6763))

**Comment by kosciCZ** [comment]
This is open to implementation now as nothing is blocking it, although it's more of a nice-to-have feature

**Comment by jpopelka** [comment]
Been looking into this and seen two problems with `fedpkg update`:
- it [opens vi](https://pagure.io/fedpkg/blob/master/f/fedpkg/cli.py#_322) to interactively edit update parameters
  - work-around could be in setting `EDITOR` env. var. to a script which would just `sed s/type=/type=bugfix/ argv[1]` (`type` is the only required unfilled field in the template text)
- fedpkg calls bodhi-client to do the actual update, but it seems that bodhi-client doesn't work with kerberos as it always asks for password even I have valid krb ticket (try yourself with `bodhi updates new xyz`)
  - looks like a blocker so far

**Comment by TomasTomecek** [comment]
@bowlofeggs, hi Randy, would you be able to help us here? Does bodhi have an API for creating updates? Is there a kerberos support in-place?

**Comment by bowlofeggs** [comment]
Hi @TomasTomecek!

Bodhi does have a REST API that allows creating updates:

https://bodhi.fedoraproject.org/docs/server_api/updates.html#service-2-POST

Most Fedora infrastructure apps do not use Kerberos (and there are not plans for them to either - I believe only Koji and the package lookaside cache use Kerberos). Bodhi currently uses OpenID for authentication, but there are [plans for it to use OpenID Connect](https://github.com/fedora-infra/bodhi/issues/1180) instead.

Bodhi does have Python bindings to the REST API, and the bindings can do the OpenID stuff for you:

https://bodhi.fedoraproject.org/docs/python_bindings.html

These bindings are used by the Bodhi CLI, so you can see its code for example usage:

https://github.com/fedora-infra/bodhi/blob/3.6.0/bodhi/client/__init__.py

**Comment by TomasTomecek** [comment]
@bowlofeggs thanks, that's so helpful!

I wonder whether it's possible to use kerberos, get authenticated via ypsilon/FAS and use those credentials for OpenID. On the other hand, even writing it down looks like too much hassle. I just wanted to avoid storing password in plaintext.

**Comment by bowlofeggs** [comment]
I think that's what OpenID Connect will help with (among other things) - I believe you will get a token you can hand to Bodhi instead of a password. Unfortunately, bodhi is still OpenID for now...

**Comment by jpopelka** [comment]
Just spotted https://pagure.io/fedobuild/

" It listens on the fedmsg bus for dist-git pushes and automatically initiates koji builds and bodhi updates."

**Comment by TomasTomecek** [comment]
We should freeze this and go in favor of https://github.com/user-cont/source-git/issues/26

Or fedobuild, as Jirka pointed out.

**Comment by TomasTomecek** [comment]
Closing since packit will handle this.
