### ISSUE TITLE
Handle setup.py with 'version', but no '__version__' ?

### ISSUE THREAD

**Issue by jpopelka** [user-cont/release-bot#129]
When we create a release PR from a release issue, we [bump](https://github.com/user-cont/release-bot/blob/master/release_bot/utils.py#L169) any `__version__` we find in `{'setup.py', '__init__.py', 'version.py'}`.

The thing is that many projects use just `version='x.y.z'` in `setup.py`. As @kosciCZ [pointed out](https://github.com/user-cont/release-bot/pull/76#discussion_r208476104), per PEP one SHOULD use `__version__`, but I'm still wondering if we can handle also the `version='x.y.z'` case ?

**Comment by Asutosh989** [comment]
I would like to work on it.

**Comment by jpopelka** [comment]
> many projects use just `version='x.y.z'` in `setup.py`.

The same applies to `setup.cfg` ([example](https://github.com/user-cont/ucho/blob/master/setup.cfg#L3))

**Comment by Toaster192** [comment]
Ready to be closed?
