### ISSUE TITLE
bodhi: also show command to run to create the updates

### ISSUE THREAD

**Issue by TomasTomecek** [user-cont/release-bot#131]
Release bot can also print a command to run in terminal to create the update.

**Comment by shresthagrawal** [comment]
Are you talking about the update of the bot it self ? Do you mean that it should check for the update in Bodhi, and if available just recommend the command that the user should use to update in Terminal.

**Comment by TomasTomecek** [comment]
The original idea was to also perform a bodhi update in Fedora once the Fedora koji builds are done. But it wasn't easy to authenticate with bodhi. Hence the workaround was to just print the bodhi command and the maintainers would run it themselves.

But since we are planning to move the fedora functionality #138 to packit, I'm going to close this issue.
