### ISSUE TITLE
RPM Changelog: use bots' credentials, not the github approver

### ISSUE THREAD

**Issue by TomasTomecek** [user-cont/release-bot#133]
This is ugly, the bot is doing the work, not me, I don't want the credit.

https://github.com/user-cont/release-bot/blob/2e79b44a9b508c2053d8be9910b2e747c0236104/release_bot/releasebot.py#L257

The bot obtains credentials of the person who approved the pull request for a new release. My expectation is that by default, bots credentials should be used in the changelog. By bots credentials I mean its username and contact email. E.g. this is our bot identity: https://github.com/usercont-release-bot

Hence I expect to see this line in the changelog:
```
* Thu Mar 22 2018 User-cont Release Bot <the-email-we@have-set-for-the.bot> - 0.6.0-1
- New upstream release 0.6.0

```

**Comment by shresthagrawal** [comment]
Hey Thomas, I wish to contribute to release bot for GSOC 2019. It would be really helpful if you can you please elaborate more about what you want in the issue and what do you exactly mean by term 'bot's credential' and 'github approver'.

**Comment by TomasTomecek** [comment]
I updated the original post, is it more clear now?

**Comment by shresthagrawal** [comment]
Yaah it is clear now

**Comment by Toaster192** [comment]
@TomasTomecek Would just getting the info from a hardcoded user 'usercont-release-bot' (and in case it fails, use the approvers details) be sufficient or would you want to cover forks of the bot and such? (maybe try to get the info by running a `git remote show origin` in the base folder or something)

**Comment by TomasTomecek** [comment]
@Toaster192 no need to handle bot's forks, they should not be used anywhere AFAIK

It turns out this may be actually just a configuration issue of our deployment: one can specify author in the config.

And as I'm thinking about this now, @rpitonak removed all Fedora and RPM-related code recently, so this is not even relevant any more, closing then.

(I think we should reintroduce the rpm-spec bumping functionality back: e.g. as a hook)
