### ISSUE TITLE
Improve guide for new users

### ISSUE THREAD

**Issue by marusinm** [user-cont/release-bot#152]
Related to #107, #33.

As a participant of RH open source contest I tried to run release-bot locally and successfully automated releases on private Github repo. However, I had to face several problems:  
- s2i isn't working without .pipyrc file, means a user cannot create just Github release and test release-bot easily. 
- I had to look up for a way how to run release-bot from cli, it'll be better have documentation with steps for cli commands like `python3 release_bot/releasebot.py -c path_to_conf.yaml --debug`
- or how to install release-bot via pip 
- Also, I don't understand why option `trigger_on_issue` in release-conf.yaml is `false` by default. Release-bot couldn't be able to create PR from issue without changing it to `true`.

**Comment by TomasTomecek** [comment]
Hi! Thanks for reaching out!

I share your frustration and that's why I started #107 back then. Sadly we didn't have enough time to address it. Hence we signed it up to the contest.

If you're brave enough to send us PRs for the issues you raised here, that would be tremendously helpful.

**Comment by marusinm** [comment]
Something like this issue could be nice for the first contribution, I will jump on it.

**Comment by TomasTomecek** [comment]
Given #161 is merged, I'm closing. Thanks for working on this!
