### ISSUE TITLE
release_bot stuck on releasing on PyPi.

### ISSUE THREAD

**Issue by Aniket-Pradhan** [user-cont/release-bot#162]
Hello There.

I was getting my hands dirty on the bot. I want the bot to not release only on GitHub and not on PyPi. I don't have any `.pypirc` file in my directory (where I have the `conf.yaml`). 

Because of this, the bot goes into a loop where it is unable to release on PyPi (since there is no .pypirc) and it ignores the latest issues on GitHub.

As an example, have a look at this [repository](https://github.com/Aniket-Pradhan/RandomEmptyRepo/). I have an open [issue](https://github.com/Aniket-Pradhan/RandomEmptyRepo/issues/4), which is ignored by the bot, and it keeps commenting on the [PR](https://github.com/Aniket-Pradhan/RandomEmptyRepo/pull/3), that it cannot release on PyPi.

Is there any such option for the bot, that I am missing? Or it can be implemented? I will be happy to help. :)

**Comment by TomasTomecek** [comment]
Hi there, thank you for taking your time trying the bot out and opening this issue.

I think you indeed found a bug!

The problem is that your instance fails here:

https://github.com/user-cont/release-bot/blob/master/release_bot/releasebot.py#L278

and is unable to get to this line:

https://github.com/user-cont/release-bot/blob/master/release_bot/releasebot.py#L282

where it should handle opened PRs.

I guess the easiest solution should be to wrap the two use cases in a try/except block.

**Comment by Aniket-Pradhan** [comment]
Thanks for the help.

>I guess the easiest solution should be to wrap the two use cases in a try/except block.

Yes. That solves the problem. However, it also gives birth (or unmasks) to another issue, where the bot is constantly looking for `.pypirc` and it keeps commenting on the **first** pull request it created.

As an example, in the same repository, the bot created a new [PR](https://github.com/Aniket-Pradhan/RandomEmptyRepo/pull/6) (release 1.0.1), but it kept commenting on the [PR](https://github.com/Aniket-Pradhan/RandomEmptyRepo/pull/3) for release 1.0.0.

Maybe we can have a config setting in the conf.yaml whether we want to make a PyPi release or not.

**Comment by TomasTomecek** [comment]
Huh, I thought we had such setting but apparently we don't. Yup, that's a good idea, the bot should not enforce PyPI release - it should be configurable.

**Comment by Aniket-Pradhan** [comment]
Can I work on that bit?

I am also sending out a pull request which fixes the original issue I raised here.

**Comment by TomasTomecek** [comment]
Yes, please! That would be lovely.

**Comment by Aniket-Pradhan** [comment]
Hey!

I have been thinking, that we just need to add a new parameter to the `release.conf` file if we want to release it on PyPi (just like it is done with the Fedora releases). The only change would be to check if that parameter is true or not. If true, then we proceed further and look for the `pypirc` file (if the file is present or not present, that's another story). Otherwise, we stop there and do other tasks (like releasing on GitHub). Am I going on the right track?

**Comment by TomasTomecek** [comment]
@Aniket-Pradhan you are absolutely correct!

**Comment by Aniket-Pradhan** [comment]
That's awesome!

I soon release a PR for this as well. ^>^

**Comment by ash753** [comment]
Hi,
I set `pypi: false` inside `release-conf.yaml` but I still get too many comments telling it failed to publish on pypi

**Comment by Aniket-Pradhan** [comment]
Which release-bot version are you using? Are you building from GitHub, or installing it using Pip?

**Comment by TomasTomecek** [comment]
Run it with --debug and you'll be able to see in logs what's wrong.

**Comment by ash753** [comment]
same as #198 and it's fixed in upstream, I was using the pypi package.
