### ISSUE TITLE
repository name != pypi name is a problem

### ISSUE THREAD

**Issue by TomasTomecek** [user-cont/release-bot#170]
We ran into this issue when doing the first release in [packit](https://github.com/packit-service/packit). The name in PyPI is packitos and sadly release-bot checked against PyPI repository packit, not packitos.

TODO:
* [ ] add a new option to config file to set PyPI project name:
  ```
  pypi_project: packitos
  ```
* [ ] optionally, try to parse the project name from setup.cfg (this is a stretch goal)

**Comment by Elias999** [comment]
Just a clarification, by the title you mean the situation when the pypi name have to be different than repository name?

**Comment by rpitonak** [comment]
@Elias999 exactly

**Comment by TomasTomecek** [comment]
@Aniket-Pradhan that's not enough, because people can have the name specified in setup.py. I'd love if the pypi repository name could be configured in the config file. I'll update the original post.

**Comment by Elias999** [comment]
I have started working on it.

**Comment by Elias999** [comment]
I just added a new line in configuration.py, "self.pypi_project = ''", should i commit now ? Also i have started to write a new function so it can parse the metadata.

**Comment by jpopelka** [comment]
@Elias999 commit, push and create a Pull Request where we can discuss the changes
