### ISSUE TITLE
implement dry-run mode

### ISSUE THREAD

**Issue by TomasTomecek** [user-cont/release-bot#171]
It would be nice if release bot had a dry run which would not perform any remote changes and would just inform about possible actions.

**Comment by Aniket-Pradhan** [comment]
I would like to work on it. :)

Will submit some changes soon.

**Comment by Aniket-Pradhan** [comment]
After looking at #138  and #176 I don't think that I should work/make changes on the Fedora-related files. Right?

**Comment by TomasTomecek** [comment]
@Aniket-Pradhan #176 is already merged, so there no Fedora-building-related changes in release-bot now. Please rebase.

**Comment by Aniket-Pradhan** [comment]
Time to close this.

Solved by #177
