### ISSUE TITLE
bot asks for GitHub credentials every time it polls, when using with a private repo

### ISSUE THREAD

**Issue by Z0Marlin** [user-cont/release-bot#179]
When using the release-bot with a private remote repository, the bot prompts for the Github credentials of the user, every time it polls from the server.
To reproduce: 
1. install `release-bot` (I used `pip` install).
2. Set up a private repository on GitHub, and the add `release-conf.yml` file in it.
3. In your local machine create the `conf.yaml` file, and enter the required options in it.
4. run the bot.

**Comment by TomasTomecek** [comment]
I'm assuming that it happens when the bot is cloning the repository -- some logs would be pretty helpful.

More thinking... If the bots does `git clone https://...` and the repo is private, it needs to provide credentials for github. So I guess we should clone using the ssh url.

https://github.com/user-cont/release-bot/blob/master/release_bot/releasebot.py#L39

Changing that to the ssh url should resolve the issue. Or make this configurable completely in the config file.

**Comment by Aniket-Pradhan** [comment]
`git clone https://<user-name>:<token>@github.com/<user-name>/<project-name>.git`

Another way to clone a repository, without asking for a password. Maybe we can replace it with the current clone function.

**Comment by TomasTomecek** [comment]
Please don't. That would make very easy for the token to leak. Let's try the ssh url first.

**Comment by Z0Marlin** [comment]
> I'm assuming that it happens when the bot is cloning the repository -- some logs would be pretty helpful.

Yes this is exactly what's happening.
```
22:31:22.925 configuration.py  DEBUG  Loaded configuration for z0marlin/Temp
Username for 'https://github.com': z0marlin
Password for 'https://z0marlin@github.com': 
22:31:32.979 utils.py          DEBUG  ['git', 'clone', 'https://github.com/z0marlin/Temp.git', '.']

22:31:32.980 releasebot.py     INFO   release-bot v0.6.1 reporting for duty!
Username for 'https://github.com': z0marlin
Password for 'https://z0marlin@github.com': 
22:31:46.617 utils.py          DEBUG  ['git', 'pull', '--rebase', 'origin', 'master']
Already up to date.
Current branch master is up to date.
```
The bot needs the credentials for performing `clone`, `pull`, or `fetch`.

**Comment by Z0Marlin** [comment]
I think we should add an option in the config to switch to ssh url, and inform the user to activate the option when working with private repos.

**Comment by TomasTomecek** [comment]
I think we should use the ssh URL by default.

**Comment by Z0Marlin** [comment]
> I think we should use the ssh URL by default.

I see. But won't that force every user to generate a key pair and set up the keys? Because if the repo is public, then SSH wouldn't be needed. Could we add an option in the configuration that allows the user to use the `https` method, and by default use the `ssh` method?

**Comment by TomasTomecek** [comment]
> But won't that force every user to generate a key pair and set up the keys?

I'd say that's a prerequisite for working with git and github :D 

Feel free to add a new field into configuration, something like:
```
clone_url: "https://github.com/foo/bar.git"
```

And everyone will be able to pick the precise URL. Otherwise, we can default to https the way it works now. WDYT?

**Comment by Z0Marlin** [comment]
Yeah, I think that will be good. Will provide the `clone_url` field in the config.
