### ISSUE TITLE
Improve Contributor's Guide

### ISSUE THREAD

**Issue by Z0Marlin** [user-cont/release-bot#183]
I think the contributing guidelines need some improvements. One such improvement would be to add a section which says something like **Development Environment**, which explains how to set up an environment to locally test the changes made in the code.

**Comment by Aniket-Pradhan** [comment]
One more improvement could be on how to utilize the test suite. I am sort of new to containers, and it took me a good jig of time to set up the Docker container.

Moreover, to run all the tests, we need to submit the Github username and token, which is not specified in the document, but in the `Makefile`.

**Comment by Toaster192** [comment]
Can be closed?
