### ISSUE TITLE
migration to pipenv for easier environment setup and management

### ISSUE THREAD

**Issue by ash753** [user-cont/release-bot#197]
I suggest to migrate to pipenv because Pipfiles are easier to manage, also we can use `.env` file to store critical environment variables which sourced automatically while issueing `$ pipenv shell` and use them inside the code using `os.environ.get()`

**Comment by TomasTomecek** [comment]
We are using containers for release-bot deployment so this doesn't bother us, upstream devs, much. Feel free to submit a PR.

**Comment by lachmanfrantisek** [comment]
We've already had discussion and ["research"](https://github.com/user-cont/kwaciaren/wiki/Pipenv-(not-used)) about that.

We agreed that it gives us no benefit and does not work well with the releasing to the Linux distributions, where you should not depend on the specific version of the required packages.

**Comment by ash753** [comment]
I've worked with Pipenv basic operation, it's just very easy to get started with, and the development environment creation will be easier for newcomers, that's the main benefit I see.
Concerning the research you @lachmanfrantisek mentioned, I suppose we shouldn't care about windows being a first class citizen, however, the first statement needs more consideration.

I will do further research and start working on it tonight to see if it is worth it.

**Comment by lachmanfrantisek** [comment]
> I've worked with Pipenv basic operation, it's just very easy to get started with, and the development environment creation will be easier for newcomers, that's the main benefit I see.

I understand. I have seen many youtube videos about Pipenv, but still cannot see the real advantage comparing the virtualenv/virtualenv-wrapper/... BTW, the two links mentioned in the wiki are very interesting.

> Concerning the research you @lachmanfrantisek mentioned, I suppose we shouldn't care about windows being a first class citizen, however, the first statement needs more consideration.

Definitely, the first one is big(er) problem. I'm just scared about duplicating the requirements. We need one place with requirements and still support standard PyPI packaging.

It would be nice if you can find some way to use somehow both systems together.

**Comment by Aniket-Pradhan** [comment]
Some two cents about my experience with `pipenv`.
I was trying out a Django application which was using `pipenv`. The installation and locking procedure (not downloading) of dependencies took almost 10 minutes! 

I agree `pipenv` is beginner friendly, but it is really slow. [Here](https://chriswarrick.com/blog/2018/07/17/pipenv-promises-a-lot-delivers-very-little/#the-part-where-i-try-to-measure-times) is a table which compares the speed of `pipenv` Here is some data related to the time consumed by `pipenv`.

Also, it is [recommended](https://unix.stackexchange.com/questions/450008/pip-vs-package-manager-for-handling-python-packages) to use your distro specific python packages, before using `pip` (**IF** you're not using a virtual environment).

**Comment by ash753** [comment]
After doing my research, I'm convinced it's not worth it. I will just add another tool that's not necessary.
