### ISSUE TITLE
the bot doesn't issue new releases because of previous pypi failure

### ISSUE THREAD

**Issue by ash753** [user-cont/release-bot#198]
I've created a `new patch release` issue in the repo but release-bot won't recognise it and will always check upon the previous PR release, and tell it's already released then comment with failure to publish on PyPi message, then goes to sleep, and so forth.

**Comment by TomasTomecek** [comment]
I thought this was already fixed in upstream, please post debug logs

**Comment by ash753** [comment]
my mistake I was using the pypi version, yes it's fixed in the upstream
