### ISSUE TITLE
Checklist for the next release

### ISSUE THREAD

**Issue by TomasTomecek** [user-cont/release-bot#202]
Since we got so much new code lately thanks to all of you guys, @rpitonak had an idea to do a new release.

Let's use this issue to track work which needs to be done to do a next minor release of release-bot.

I hope we could do this mid-April. WDYT?

TODO
* [x] perform a release using git master code from release-bot (I released ansible-bender 0.5.2 using the code in git master)
* [x] merge #182 (we need it for packit)

**Comment by Aniket-Pradhan** [comment]
I guess we can finish up with the open PRs before a new release?

I was also thinking #105 or #141 could also be pushed into this release because they seem to be not that big (I might be wrong) and to close some old issues. 

All the other issues seem big enough that can be included in a single release.

**Comment by Z0Marlin** [comment]
I think a lot of changes and new features have been added. We can safely make a release now. And yeah I agree with @Aniket-Pradhan that we can should the open PRs and then make the release.

**Comment by TomasTomecek** [comment]
@Aniket-Pradhan I propose to not work on new things: let's just clean up and release.

The gitchangelog+init PR is pretty big: we should make sure it works well before merging and releasing it.

**Comment by TomasTomecek** [comment]
@rpitonak since this is your idea, can you take care of the release? :D

**Comment by rpitonak** [comment]
@TomasTomecek sure!

**Comment by marusinm** [comment]
+1 for release. If you will need any help with testing or whatever I'm ready.

**Comment by rpitonak** [comment]
Thank you all for offering help!

I am going to make a new release by the end of this week. I would be glad for your reviews once release PR is done!

**Comment by rpitonak** [comment]
[0.7.0 release](https://github.com/user-cont/release-bot/releases/tag/0.7.0)
