### ISSUE TITLE
[RFE] Make `refresh_interval` optional to allow the bot to run only once

### ISSUE THREAD

**Issue by CermakM** [user-cont/release-bot#248]
There are times I want to run the bot only once and exit immediately. A simple way to do this would be making the `refresh_interval` optional and if not provided, run only once and exit.

*EDIT* The `refresh_interval` already is optional, however, a default value is used when not specified.

**Comment by jpopelka** [comment]
I see your point Marku, but re-using `refresh_interval` the way you suggest would change the default behavior.

We already have [--dry-run cli argument](https://github.com/user-cont/release-bot/blob/master/release_bot/cli.py#L39).
So what about adding also something like `--run-once` or `--no-loop`? (more suggestions welcome)

**Comment by CermakM** [comment]
It wouldn't change the default behaviour, it would change the default configuration. I personally see no point in having `refresh_interval` defined unless I do want the bot to do the refresh and I find it confusing --- I would expect the bot to run once unless I explicitly tell it to refresh.

I initially thought about having the `--run-once` argument to the CLI. The problem is that it would decouple the configuration from the actual execution, which is not ideal in my opinion. In either way, it would serve the purpose as well so it's your decision :).

Further context: I've been working on [turning Release Bot into a GitHub Action](https://github.com/CermakM/python-release-action) and make it part of a Release Workflow and I do need to only run the bot once for that.

**Comment by jpopelka** [comment]
> It wouldn't change the default behaviour, it would change the default configuration.
> I would expect the bot to run once unless I explicitly tell it to refresh

fair enough, I think I'm fine with the change then

> I've been working on [turning Release Bot into a GitHub Action](https://github.com/CermakM/python-release-action)

Wow! Not sure if it helps you, but it should be possible to [run release bot as a Github App](#237 ) soon.

**Comment by CermakM** [comment]
Yep, I am aware of that, but the problem with GitHub App is that it requires
a) user-provided token
b) all of the configuration to be present in the repo
c) a server to run on

None if this is required for the Action. I am gonna share updates with you guys once I make it work.

Currently, I am getting some nasty errors, feel free to check it out at https://github.com/CermakM/test/runs/268139764

**Comment by jpopelka** [comment]
Changed in #250
