### ISSUE TITLE
Write guide for new users

### ISSUE THREAD

**Issue by kosciCZ** [user-cont/release-bot#33]
The best example is bot itself as it releases itself to PyPi. Write a detailed guide on how to get the bot running and provide real configuration examples from this repository. 

This issue is from code review issue #27.

Update: this is a very good candidate for Google Summer of {Docs,Code} or Red Hat Open Source Contest.

**Comment by TomasTomecek** [comment]
Is this still needed? Can we just link to @phracek's blog post on opensource.com?

**Comment by TomasTomecek** [comment]
Okay, we need this really badly. I am having such hard times configuring the bot. E.g. pypirc is such a pain.

**Comment by TomasTomecek** [comment]
#161 fixed this
