### ISSUE TITLE
`fedpkg clone` doesn't work in anyuid openshift environment

### ISSUE THREAD

**Issue by TomasTomecek** [user-cont/release-bot#48]
Since containers in openshift can have a random uid, fedpkg is not able to get a username b/c there is no such entry in /etc/passwd:
```
14:17:38.981 release_bot.py    DEBUG  ['fedpkg', 'clone', 'conu']
14:17:38.982 release_bot.py    ERROR  Cloning fedora repository failed:
Traceback (most recent call last):
  File "/usr/bin/fedpkg", line 11, in <module>
    load_entry_point('fedpkg==1.32', 'console_scripts', 'fedpkg')()
  File "/usr/lib/python2.7/site-packages/fedpkg/__main__.py", line 58, in main
    client.parse_cmdline()
  File "/usr/lib/python2.7/site-packages/pyrpkg/cli.py", line 1804, in parse_cmdline
    self.user = pwd.getpwuid(os.getuid())[0]
KeyError: 'getpwuid(): uid not found: 1005350000'
```

**Comment by jpopelka** [comment]
I see.
If pyrpkg was using [getpass.getuser()](https://docs.python.org/3/library/getpass.html#getpass.getuser) instead of directly [pwd.getpwuid(os.getuid())[0]](https://pagure.io/rpkg/blob/master/f/pyrpkg/cli.py#_1804) we could avoid this by setting an env. variable (LOGNAME, USER, LNAME and USERNAME)

**Comment by jpopelka** [comment]
Hmm, even with patched rpkg, the underlying git clone fails due to the same problem (no user for uid):

```
docker run -ti -u 105 release-bot-app:dev bash
bash-4.4$ git config --global user.name usercont
bash-4.4$ git config --global user.email usercont@rh.com
bash-4.4$ export LOGNAME='usercont'
bash-4.4$ kinit usercont@FEDORAPROJECT.ORG -k -t fedora.keytab
bash-4.4$ fedpkg clone conu
Cloning into 'conu'...
No user exists for uid 105
fatal: Could not read from remote repository.

Could not execute clone: Command '['git', 'clone', 'ssh://usercont@pkgs.fedoraproject.org/rpms/conu', '--origin', 'origin']' returned non-zero exit status 128
bash-4.4$ git clone ssh://usercont@pkgs.fedoraproject.org/rpms/conu --origin origin 
Cloning into 'conu'...
No user exists for uid 105
fatal: Could not read from remote repository.
```

**Comment by TomasTomecek** [comment]
fudge, I fear we need something like this:

https://github.com/sclorg/postgresql-container/blob/4a7ce3eef2b322882c4a14b863aa81fc0cd4dab9/src/root/usr/share/container-scripts/postgresql/common.sh#L145

Or fix git.

**Comment by jpopelka** [comment]
Thanks, that helps, but still no luck (I have valid krb ticket)

```
bash-4.4$ fedpkg clone conu
Cloning into 'conu'...
The authenticity of host 'pkgs.fedoraproject.org' can't be established.
Are you sure you want to continue connecting (yes/no)? yes
usercont@pkgs.fedoraproject.org: Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
Could not execute clone: Command '['git', 'clone', 'ssh://usercont@pkgs.fedoraproject.org/rpms/conu', '--origin', 'origin']' returned non-zero exit status 128
```

**Comment by jpopelka** [comment]
Uh, now I'm getting `Could not create directory '/.ssh'.` while having no idea what I'm doing differently than in previous comment.

**Comment by TomasTomecek** [comment]
could it be that it's trying to create a dir in `$HOME/.ssh` and `HOME=`; setting home to `HOME=/tmp` could help

**Comment by jpopelka** [comment]
`$HOME` is set to `/opt/app-root/src` in [Dockerfile](https://github.com/user-cont/release-bot/blob/master/Dockerfile#L6) and I don't see the '.ssh' problem now (I must have misconfigured something when writing my previous comment), just the
https://github.com/user-cont/release-bot/issues/48#issuecomment-388104020
