### ISSUE TITLE
Add Integration / End-to-End  tests

### ISSUE THREAD

**Issue by jpopelka** [user-cont/release-bot#65]
We probably won't be able to test Fedora releasing (I guess you can't have "a testing" package in Fedora), but we should be able to verify that releasing to github & PyPI (https://test.pypi.org/) works correctly.

**Comment by TomasTomecek** [comment]
There could be a staging instance of Fedora services (dist-git and bodhi) to verify against.

**Comment by kosciCZ** [comment]
I'm looking into testing the releasing on Github. From what I gathered, I think the correct way to approach this is following:

1) Have usercont-release-bot create a new github repository with randomly generated name (having one testing repository could cause issues if more than one test would run at the same time - for example: a PR is made right after another one was opened, or someone runs test locally)
2) Setup basic python package, kinda like [this](https://github.com/kosciCZ/bot-test-repo) 
3) Make bot release it - this is when current implementation falls short - it has a problem, if there are no previous releases, or package is not yet release on PyPi. 
4) Check release was made on both platforms
5) Delete Github repo and return result

Possible problem is exposing personal tokens and such, luckily, Travis CI offers [a way](https://docs.travis-ci.com/user/encryption-keys/) to encrypt sensitive data. 

I'm gonna go ahead and work on implementing this, but I'll be grateful for any comments or suggestions.

**Comment by TomasTomecek** [comment]
wouldn't it be easier to mock all the remote APIs?

**Comment by kosciCZ** [comment]
I considered this and I think it would be harder to do, i.e.  github v4 api uses GraphQL where for example iterating through PRs/ issues isn't trivial. And if I mocked the entire function to simplify that, I wouldn't really test it. 

What I described above isn't that hard to do, it's just few more api calls, so that is why I decided to go with it.

**Comment by kosciCZ** [comment]
Closing this, as it was fixed by #78
