### ISSUE TITLE
RFE: Run bot as a cronjob in OpenShift

### ISSUE THREAD

**Issue by fridex** [user-cont/release-bot#75]
Are there any reasons why the bot is sleeping on CPU? Our similar bots run as a cronjob so they do not waste CPU resources. To reduce overhead needed for the pod spinning up for a single repo, the bot could accept a list of repositories in the `conf.yaml` to be checked and issue new releases for.

**Comment by fridex** [comment]
Or probably even better solution - trigger the bot based on git hooks.

**Comment by TomasTomecek** [comment]
These are really good suggestions.

**Comment by TomasTomecek** [comment]
Our plan with release-bot is to utilize Github webhooks so I'm closing this in favor of https://github.com/user-cont/release-bot/issues/112
