### ISSUE TITLE
Don't try to release old releases

### ISSUE THREAD

**Issue by TomasTomecek** [user-cont/release-bot#77]
Seems like the bot is trying to release old releases.

https://github.com/user-cont/colin/pull/138#issuecomment-409615690

**Comment by jpopelka** [comment]
Yes, the way it works is that we take a look at the latest merged PR and try to release the version on github and github is [supposed to](https://github.com/user-cont/release-bot/blob/master/release_bot/github.py#L156) tell us that such release already exists. However from time to time it does not for unknown reasons.

This is duplicate of #72

**Comment by TomasTomecek** [comment]
I don't think this is a dupe, they are different -- the other one is about comments, a consequence, while this one is the reason.

Would it help to check for the release first?
