### ISSUE TITLE
0.4.0 release

### ISSUE THREAD

**Issue by jpopelka** [user-cont/release-bot#79]
I've updated the self-releasing release-bot (release-bot-user-cont) on Openshift, so let's test the new feature (#76)

**Comment by jpopelka** [comment]
re-building, re-deploying, stay tuned

**Comment by kosciCZ** [comment]
This is just like watching Superbowl!

**Comment by jpopelka** [comment]
Whut ??? How/when he did that when he failed to re-deploy ???
