### ISSUE TITLE
Who should be able to trigger the bot by issue?

### ISSUE THREAD

**Issue by kosciCZ** [user-cont/release-bot#82]
This was surfaced when @rpitonak tried to release conu through an issue, not being in the user-cont organization, but still being an invited collaborator. Right now bot allows people with ADMIN or MEMBER [association](https://developer.github.com/v4/enum/commentauthorassociation/) ([see relevant code here](https://github.com/user-cont/release-bot/blob/master/release_bot/releasebot.py#L80)) to trigger a release with an issue. Is it desirable to allow this for people with COLLABORATOR association?

**Comment by TomasTomecek** [comment]
yes, collaborator, member and admin should be good enough; or: make it configurable, or utilize some sort of voting system;

but still, if someone with those privs creates an issue, the bot should create the new release PR (anyone can do that, really) and this should be approved by a commiter
