### ISSUE TITLE
label on release issues and PRs

### ISSUE THREAD

**Issue by rpitonak** [user-cont/release-bot#85]
It would be nice, if release bot would put `release-bot` label on release issue and PR.

**Comment by TomasTomecek** [comment]
What would be the semantics? Just that it interacted with the issues/PR?

**Comment by TomasTomecek** [comment]
[why are those buttons so close to each other -_-]

**Comment by rpitonak** [comment]
Yes, basically when you open an issue `x.y.z release`, bot will put label `release-bot` on it. Same with PR. It will keep issue and PR list more organized, because we already use labels from another bots, for example in conu.

**Comment by kosciCZ** [comment]
This was fixed by #94, so I think it's okay to close this issue.
