### ISSUE TITLE
RFE: Update setup.py with higher number if version does not exist

### ISSUE THREAD

**Issue by phracek** [user-cont/release-bot#97]
I would prefer to implement a new mechanishm if version.py file does not exist.

I would prefer to update setup.py file into higher version.

Does it make sense to you?

**Comment by kosciCZ** [comment]
We did consider this, but according to PEP 396, version should be derived from `__version__` variable, so implementing changing directly the version entry in `setup.py` is kind of going against best practices from my point of view. See my [comment](https://github.com/user-cont/release-bot/pull/76#discussion_r208476104) on relevant PR for details.

What does @jpopelka think?

**Comment by TomasTomecek** [comment]
I agree with Honza. There are definitely more ways how this could be done right (usage of `__version__`, e.g. have it in `__init__.py` directly).
